import sqlalchemy as sa

from app import db
from app.models import Teams


def updateLogos():
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Arizona Diamondbacks')
                       .values(team_logo='/static/logos/arizonaDiamondbacks.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Atlanta Braves')
                       .values(team_logo='/static/logos/atlanteBraves.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Baltimore Orioles')
                       .values(team_logo='/static/logos/baltimoreOrioles.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Boston Red Sox')
                       .values(team_logo='/static/logos/bostonRedSox.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Chicago Cubs')
                       .values(team_logo='/static/logos/chicagoCubs.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Chicago White Sox')
                       .values(team_logo='/static/logos/chicagoWhiteSox.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Cincinnati Reds')
                       .values(team_logo='/static/logos/cincinnatiReds.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Colorado Rockies')
                       .values(team_logo='/static/logos/coloradoRockies.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Detroit Tigers')
                       .values(team_logo='/static/logos/detroitTigers.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Houston Astros')
                       .values(team_logo='/static/logos/houstonAstros.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Kansas City Royals')
                       .values(team_logo='/static/logos/kansasCityRoyals.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Los Angeles Angels')
                       .values(team_logo='/static/logos/losAngelesAngels.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Los Angeles Dodgers')
                       .values(team_logo='/static/logos/losAngelesDodgers.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Miami Marlins')
                       .values(team_logo='/static/logos/miamiMarlins.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Milwaukee Brewers')
                       .values(team_logo='/static/logos/milwaukeeBrewers.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'New York Mets')
                       .values(team_logo='/static/logos/newYorkMets.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'New York Yankees')
                       .values(team_logo='/static/logos/newYorkYankees.png'))
    db.session.execute(sa.update(Teams).where(Teams.team_name == 'Oakland Athletics')
                       .values(team_logo='/static/logos/oaklandAthletics.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Philadelphia Phillies')
                       .values(team_logo='/static/logos/philadelphiaPhillies.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Pittsburgh Pirates')
                       .values(team_logo='/static/logos/pittsburghPirates.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'San Diego Padres')
                       .values(team_logo='/static/logos/sanDiegoPadres.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'San Francisco Giants')
                       .values(team_logo='/static/logos/sanFranciscoGiants.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Seattle Mariners')
                       .values(team_logo='/static/logos/seattleMariners.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'St. Louis Cardinals')
                       .values(team_logo='/static/logos/stLouisCardinals.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Tampa Bay Rays')
                       .values(team_logo='/static/logos/tampaBayRays.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Texas Rangers')
                       .values(team_logo='/static/logos/texasRangers.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Toronto Blue Jays')
                       .values(team_logo='/static/logos/torontoBlueJays.png'))
    db.session.execute(db.update(Teams).where(Teams.team_name == 'Washington Nationals')
                       .values(team_logo='/static/logos/washingtonNationals.png'))
    db.session.commit()

    print("Logos Updated")
