import csv

#mapping: 
# 2023 data mapping: current = new
# teams_ID = autogenerated
# teamID = teamID
# yearId = yearID
# lgID = lgID
# divID = divID
# franchID = franchID
# team_name = name
# team_rank = Rank
# team_G = G
# team_G_home = GHome
# team_W = W
# team_L = L
# DivWin = DivWin
# WCWin = WCWin
# LgWin = LgWin
# WSWin = WSWin
# team_R = R
# team_AB = AB
# team_H = H
# team_2B = 2B
# team_3B = 3B
# team_HR = HR
# team_BB = BB
# team_SO = SO
# team_SB = SB
# team_CS = CS
# team_HBP = HBP
# team_SF = SF
# team_RA = RA
# team_ER = ER
# team_ERA = ERA
# team_CG = CG
# team_SHO = SHO
# team_SV = SV
# team_IPouts = IPouts
# team_HA = HA
# team_HRA = HRA
# team_BBA = BBA
# team_SOA = SOA
# team_E = E
# team_DP = DP
# team_FP = FP
# park_name = park
# team_attendance = attendance
# team_BPF = BPF
# team_PPF = PPF
# team_projW = 
# team_projL =

import pymysql
from dbConfig import mysql

# Connect to the MariaDB database
cnx = pymysql.connect(host=mysql['host'],
                             user=mysql['user'],
                             password=mysql['password'],
                             db=mysql['database'])

cursor = cnx.cursor()

# Open the CSV file
with open('/home/wesley/Documents/DatabasesProject/SpringSpeegle/Python Scripts/Teams.csv', 'r') as file:
    reader = csv.DictReader(file)

    # Iterate over each row in the CSV file
    for row in reader:
        # Extract the data from the row based on the mappings
        teamID = row['teamID']
        yearID = row['yearID']
        lgID = row['lgID']
        divID = row['divID']
        franchID = row['franchID']
        team_name = row['name']
        team_rank = row['Rank']
        team_G = row['G']
        team_G_home = row['GHome']
        team_W = row['W']
        team_L = row['L']
        DivWin = row['DivWin']
        WCWin = row['WCWin']
        LgWin = row['LgWin']
        WSWin = row['WSWin']
        team_R = row['R']
        team_AB = row['AB']
        team_H = row['H']
        team_2B = row['2B']
        team_3B = row['3B']
        team_HR = row['HR']
        team_BB = row['BB']
        team_SO = row['SO']
        team_SB = row['SB']
        team_CS = row['CS']
        team_HBP = row['HBP']
        team_SF = row['SF']
        team_RA = row['RA']
        team_ER = row['ER']
        team_ERA = row['ERA']
        team_CG = row['CG']
        team_SHO = row['SHO']
        team_SV = row['SV']
        team_IPouts = row['IPouts']
        team_HA = row['HA']
        team_HRA = row['HRA']
        team_BBA = row['BBA']
        team_SOA = row['SOA']
        team_E = row['E']
        team_DP = row['DP']
        team_FP = row['FP']
        park_name = row['park']
        team_attendance = row['attendance']
        team_BPF = row['BPF']
        team_PPF = row['PPF']
        team_projW = row['team_projW']
        team_projL = row['team_projL']

        # Update the database with the extracted data
        query = """
        INSERT INTO teams
        (teamID, yearID, lgID, divID, franchID, team_name, team_rank, team_G, team_G_home, team_W, team_L,
        DivWin, WCWin, LgWin, WSWin, team_R, team_AB, team_H, team_2B, team_3B, team_HR, team_BB, team_SO,
        team_SB, team_CS, team_HBP, team_SF, team_RA, team_ER, team_ERA, team_CG, team_SHO, team_SV,
        team_IPouts, team_HA, team_HRA, team_BBA, team_SOA, team_E, team_DP, team_FP, park_name,
        team_attendance, team_BPF, team_PPF, team_projW, team_projL)
        VALUES
        (%s ,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
        %s ,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
        %s ,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
        %s ,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
        values = (teamID, yearID, lgID, divID, franchID, team_name, team_rank, team_G, team_G_home, team_W, team_L,
                  DivWin, WCWin, LgWin, WSWin, team_R, team_AB, team_H, team_2B, team_3B, team_HR, team_BB, team_SO,
                  team_SB, team_CS, team_HBP, team_SF, team_RA, team_ER, team_ERA, team_CG, team_SHO, team_SV,
                  team_IPouts, team_HA, team_HRA, team_BBA, team_SOA, team_E, team_DP, team_FP, park_name,
                  team_attendance, team_BPF, team_PPF, team_projW, team_projL, teamID, yearID)
        cursor.execute(query, values)

# Commit the changes and close the connection
cnx.commit()
cursor.close()
cnx.close()